-- ================== --
--     GAME_EVENT     --
-- ================== --

ALTER TABLE `game_event` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
				
UPDATE `game_event` set `description`='Festival de Solsticio' where `eventEntry`='1';
UPDATE `game_event` set `description`='Festival de Invierno' where `eventEntry`='2';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Bosque de Terokkar)' where `eventEntry`='3';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Bosque de Elwynn)' where `eventEntry`='4';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Mulgore)' where `eventEntry`='5';
UPDATE `game_event` set `description`='Año Nuevo' where `eventEntry`='6';
UPDATE `game_event` set `description`='Festival Lunar' where `eventEntry`='7';
UPDATE `game_event` set `description`='Amor en el Aire' where `eventEntry`='8';
UPDATE `game_event` set `description`='Jardín Noble' where `eventEntry`='9';
UPDATE `game_event` set `description`='Semana de los Niños' where `eventEntry`='10';
UPDATE `game_event` set `description`='Festival de la Cosecha' where `eventEntry`='11';
UPDATE `game_event` set `description`='Halloween' where `eventEntry`='12';
UPDATE `game_event` set `description`='Refuerzos para Anh Qiraj' where `eventEntry`='22';
UPDATE `game_event` set `description`='Invasión de la Plaga' where `eventEntry`='17';
UPDATE `game_event` set `description`='Invasión de Elementales' where `eventEntry`='13';
UPDATE `game_event` set `description`='Va a comenzar la Fiesta de la Pesca en Tuercespina' where `eventEntry`='14';
UPDATE `game_event` set `description`='Captura del Botín en Gurubashi Arena' where `eventEntry`='16';
UPDATE `game_event` set `description`='Fiesta de la Pesca en Tuercespina' where `eventEntry`='15';
UPDATE `game_event` set `description`='Llamamiento a las Armas:¡ Valle de Alterac!' where `eventEntry`='18';
UPDATE `game_event` set `description`='Llamamiento a las Armas: ¡Garganta Grito de Guerra!' where `eventEntry`='19';
UPDATE `game_event` set `description`='Llamamiento a las Armas: ¡Cuenca de Arathi!' where `eventEntry`='20';
UPDATE `game_event` set `description`='Llamamiento a las Armas: ¡Ojo de la Tormenta!' where `eventEntry`='21';
UPDATE `game_event` set `description`='¡Los Lobos Atacan Orgrimmar (Grupo Dos)!' where `eventEntry`='24';
UPDATE `game_event` set `description`='¡Los Lobos Atacan Orgrimmar (Grupo Uno)!' where `eventEntry`='23';
UPDATE `game_event` set `description`='¡Festival de la Cerveza!' where `eventEntry`='26';
UPDATE `game_event` set `description`='¡La Legión Ardiente ataca Ventormenta!' where `eventEntry`='28';
UPDATE `game_event` set `description`='Construcción de la Feria de la Luna Negra (Bosque de Elwynn)' where `eventEntry`='31';
UPDATE `game_event` set `description`='Culto Crepuscular y Invasión  Elementa' where `eventEntry`='48';
UPDATE `game_event` set `description`='¡Orgrimmar se defiende de los Lobos!' where `eventEntry`='25';
UPDATE `game_event` set `description`='Concierto de los L70ETC en Bosque Terokkar' where `eventEntry`='34';
UPDATE `game_event` set `description`='Locura de Espadas, Gri\'lek' where `eventEntry`='35';
UPDATE `game_event` set `description`='Locura de Espadas, Hazza\'rah' where `eventEntry`='36';
UPDATE `game_event` set `description`='Locura de Espadas, Renataki' where `eventEntry`='37';
UPDATE `game_event` set `description`='Locura de Espadas, Wushoolay' where `eventEntry`='38';
UPDATE `game_event` set `description`='Anochece, ¡Vienen los Hombres Lobo a Piroleña!' where `eventEntry`='29';
UPDATE `game_event` set `description`='Día de los Piratas' where `eventEntry`='32';
UPDATE `game_event` set `description`='Festividad de los Muertos' where `eventEntry`='40';
UPDATE `game_event` set `description`='Generosidad del Peregrino' where `eventEntry`='41';
UPDATE `game_event` set `description`='Llamamiento a las Armas: Isla de la Conquista' where `eventEntry`='42';
UPDATE `game_event` set `description`='Sentencia bajo ataque' where `eventEntry`='43';
UPDATE `game_event` set `description`='Ataque demoniaco a Thrallmar' where `eventEntry`='44';
UPDATE `game_event` set `description`='Competición de pesca Kalu\'ak' where `eventEntry`='45';
UPDATE `game_event` set `description`='Lamamiento a las Armas: ¡Playa de los Ancestros!' where `eventEntry`='30';
UPDATE `game_event` set `description`='Enero' where `eventEntry`='50';
UPDATE `game_event` set `description`='Febrero' where `eventEntry`='51';
UPDATE `game_event` set `description`='Marzo' where `eventEntry`='52';
UPDATE `game_event` set `description`='Abril' where `eventEntry`='53';
UPDATE `game_event` set `description`='Mayo' where `eventEntry`='54';
UPDATE `game_event` set `description`='Junio' where `eventEntry`='55';
UPDATE `game_event` set `description`='Julio' where `eventEntry`='56';
UPDATE `game_event` set `description`='Agosto' where `eventEntry`='57';
UPDATE `game_event` set `description`='Septiembre' where `eventEntry`='58';
UPDATE `game_event` set `description`='Octubre' where `eventEntry`='59';
UPDATE `game_event` set `description`='Noviembre' where `eventEntry`='60';
UPDATE `game_event` set `description`='Diciembre' where `eventEntry`='61';
UPDATE `game_event` set `description`='La caída de Zalazane' where `eventEntry`='46';
UPDATE `game_event` set `description`='Operación: Gnomeregan' where `eventEntry`='47';
UPDATE `game_event` set `description`='Pesca (temporada de invierno)' where `eventEntry`='64';
UPDATE `game_event` set `description`='Pesca (temporada de verano)' where `eventEntry`='65';
UPDATE `game_event` set `description`='Pesca (00.00-06.00)' where `eventEntry`='66';
UPDATE `game_event` set `description`='Pesca (06.00-12.00)' where `eventEntry`='67';
UPDATE `game_event` set `description`='Pesca (12.00-18.00)' where `eventEntry`='68';
UPDATE `game_event` set `description`='Pesca (18.00-00.00)' where `eventEntry`='69';
UPDATE `game_event` set `description`='¡Ventormenta se defiende de la Legión Ardiente!' where `eventEntry`='27';
UPDATE `game_event` set `description`='Los líderes de Jin\'Alai, Gawanil' where `eventEntry`='33';
UPDATE `game_event` set `description`='Los líderes de Jin\'Alai, Chulo' where `eventEntry`='39';
UPDATE `game_event` set `description`='Festival de Invierno: Regalos' where `eventEntry`='49';
UPDATE `game_event` set `description`='La Ciudad de Ventormenta Bajo Ataque' where `eventEntry`='77';
UPDATE `game_event` set `description`='La Ciudad de Orgrimmar Bajo Ataque' where `eventEntry`='78';
UPDATE `game_event` set `description`='Bajo Ataque JvJ Gurubashi Arena' where `eventEntry`='109';
UPDATE `game_event` set `description`='La Legión Ataca La Ciudad de Shattrath' where `eventEntry`='101';
UPDATE `game_event` set `description`='Invasión de Conejos en Dalaran' where `eventEntry`='105';
UPDATE `game_event` set `description`='Taberna del Fin del Mundo - Anuncio de Perry Gatner' where `eventEntry`='62';
UPDATE `game_event` set `description`='Taberna del Fin del Mundo - Perry Gatner Levanta el Telón' where `eventEntry`='63';
UPDATE `game_event` set `description`='Taberna del Fin del Mundo - Anuncio del concierto de L70ETC' where `eventEntry`='70';
UPDATE `game_event` set `description`='Taberna del Fin del Mundo - Concierto de L70ETC' where `eventEntry`='71';
UPDATE `game_event` set `description`='Ciudad de Ventormenta - Fuga de las Mazmorras' where `eventEntry`='72';
